apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  serviceAccount: my-service-account
  containers:
  - name: alpine
    image: alpine:latest
    command:
      - tail
      - "-f"
      - /dev/null
