apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default
  ### Warning: metadata.clusterName was specified. This field is not preserved and will be removed from the schema in 1.25
  ### serviceaccount/my-service-account created
  clusterName: my-cluster 
#   uid: 9f6377f3-5b29-4952-8dc3-7f1f76ea403e
# automountServiceAccountToken: false
